---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: create token role check_mode exists
      hashivault_token_role:
        name: testrole
        config:
          allowed_policies:
            - tokenrole_test_policy
        state: present
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "{{vault_role_create.changed}} == False" }
    - assert: { that: "{{vault_role_create.rc}} == 0" }

    - name: create token role check_mode does not exist
      hashivault_token_role:
        name: testrole_two
        config:
          allowed_policies:
            - tokenrole_test_policy
        state: present
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "{{vault_role_create.changed}} == True" }
    - assert: { that: "{{vault_role_create.rc}} == 0" }

    - name: delete token role check_mode exists
      hashivault_token_role:
        name: testrole
        state: absent
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "{{vault_role_create.changed}} == True" }
    - assert: { that: "{{vault_role_create.rc}} == 0" }

    - name: delete token role check_mode does not exist
      hashivault_token_role:
        name: testrole_two
        state: absent
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "{{vault_role_create.changed}} == False" }
    - assert: { that: "{{vault_role_create.rc}} == 0" }
