---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: create ssh role check_mode exists
      hashivault_ssh_role:
        name: testrole
        config:
          key_type: ca
          allowed_users: sshrole_test_user
        state: present
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "{{vault_role_create.changed}} == False" }
    - assert: { that: "{{vault_role_create.rc}} == 0" }

    - name: create ssh role check_mode does not exist
      hashivault_ssh_role:
        name: testrole_two
        config:
          key_type: ca
          allowed_users: sshrole_test_user
        state: present
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "{{vault_role_create.changed}} == True" }
    - assert: { that: "{{vault_role_create.rc}} == 0" }

    - name: delete ssh role check_mode exists
      hashivault_ssh_role:
        name: testrole
        state: absent
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "{{vault_role_create.changed}} == True" }
    - assert: { that: "{{vault_role_create.rc}} == 0" }

    - name: delete ssh role check_mode does not exist
      hashivault_ssh_role:
        name: testrole_two
        state: absent
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "{{vault_role_create.changed}} == False" }
    - assert: { that: "{{vault_role_create.rc}} == 0" }
